# FROM node:10
FROM python:3.7.4

COPY localstack_socless_setup.py /

RUN pip install boto3 

CMD ["python3", "localstack_socless_setup.py"]

# RUN git clone https://www.github.com/twilio-labs/socless

# RUN cd socless && npm install


## Copy the requirements and install them
# COPY requirements.txt /
# RUN pip install --upgrade pip && pip install -r requirements.txt
# RUN pip install awscli --upgrade

## Copy the needed files into the container
# COPY conf ./conf

# EXPOSE 80
