# Dynamodb Tables
Resources:
  # Slack User info to slack_ids table
  SlackUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: socless_slack_users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - slack_id
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10

# Resource outputs
Outputs:
  # Slack Usernames Table name
  SlackUsersTable:
    Description: "SOCless Slack userinfo to slack_ids table"
    Value:
      Ref: SlackUsersTable
